opt_in_rules:
    - anyobject_protocol
    - array_init
    - attributes
    - capture_variable
    - closure_spacing
    - collection_alignment
    - conditional_returns_on_newline
    - contains_over_filter_count
    - contains_over_filter_is_empty
    - contains_over_first_not_nil
    - contains_over_range_nil_comparison
    - convenience_type
    - discouraged_assert
    - discouraged_object_literal
    - discouraged_optional_boolean
    - discouraged_optional_collection
    - empty_collection_literal
    - empty_count
    - empty_string
    - explicit_init
    - explicit_self
    - extension_access_modifier
    - fallthrough
    - fatal_error_message
    - file_name_no_space
    - file_types_order
    - first_where
    - flatmap_over_map_reduce
    - force_unwrapping
    - function_default_parameter_at_end
    - ibinspectable_in_extension
    - identical_operands
    - implicitly_unwrapped_optional
    - indentation_width
    - joined_default_parameter
    - last_where
    - legacy_multiple
    - legacy_objc_type
    - legacy_random
    - let_var_whitespace
    - literal_expression_end_indentation
    - lower_acl_than_parent
    - modifier_order
    - multiline_arguments
    - multiline_arguments_brackets
    - multiline_function_chains
    - multiline_literal_brackets
    - multiline_parameters
    - multiline_parameters_brackets
    - multiple_closures_with_trailing_closure
    - no_extension_access_modifier
    - no_grouping_extension
    - number_separator
    - operator_usage_whitespace
    - overridden_super_call
    - override_in_extension
    - pattern_matching_keywords
    - prefer_self_type_over_type_of_self
    - prefer_zero_over_explicit_init
    - private_action
    - private_outlet
    - private_subject
    - prohibited_super_call
    - reduce_into
    - redundant_nil_coalescing
    - redundant_type_annotation
    - sorted_first_last
    - sorted_imports
    - static_operator
    - strict_fileprivate
    - strong_iboutlet
    - toggle_bool
    - trailing_closure
    - type_contents_order
    - unavailable_function
    - unneeded_parentheses_in_closure_argument
    - unowned_variable_capture
    - untyped_error_in_catch
    - unused_declaration
    - unused_import
    - vertical_parameter_alignment_on_call
    - vertical_whitespace_between_cases
    - vertical_whitespace_closing_braces
    - vertical_whitespace_opening_braces
    - yoda_condition

included:
    - Sources
    - Tests

multiline_arguments:
    only_enforce_after_first_closure_on_first_line: true

type_contents_order:
    order:
        - case
        - type_alias
        - associated_type
        - ib_outlet
        - ib_inspectable
        - subtype
        - type_property
        - instance_property
        - initializer
        - deinitializer
        - type_method
        - view_life_cycle_method
        - other_method
        - subscript
        - ib_action

warning_threshold: 1
